package de.SweetCode.e.input;

import de.SweetCode.e.input.entries.KeyEntry;
import de.SweetCode.e.input.entries.MouseEntry;
import de.SweetCode.e.input.entries.MouseMovingEntry;
import de.SweetCode.e.input.entries.MouseWheelEntry;
import de.SweetCode.e.utils.ToString.ToStringBuilder;

import java.awt.event.*;
import java.util.LinkedList;

/**
 * <p>
 * An InputEntry is a basic wrapper class containing information generated by a {@link Input} instance and can easily
 * by generated by calling {@link Input#build()}.
 * </p>
 */
public class InputEntry {

    private final LinkedList<KeyEntry> keyEntries;
    private final LinkedList<MouseEntry> mouseEntries;
    private final LinkedList<MouseEntry> mouseReleasedQueue;
    private final LinkedList<MouseEntry> mouseDraggedEntries;
    private final LinkedList<MouseEntry> mouseMovedEntries;
    private final LinkedList<MouseMovingEntry> mouseMovingEntries;
    private final LinkedList<MouseWheelEntry> mouseWheelEntries;

    /**
     * <p>
     *    Creates a new instance of InputEntry.
     * </p>
     *
     * @param keyEntries All key entries from the keyboard.
     * @param mouseEntries All mouse entries from normal clicks.
     * @param mouseWheelEntries All mouse entries from the mouse wheel.
     * @param mouseDraggedEntries All mouse entries from mouse dragging.
     * @param mouseMovedEntries All mouse entries from mouse movement.
     * @param mouseReleasedQueue All mouse entries from mouse releases.
     * @param mouseMovingEntries All mouse entries from the movement of itself.
     */
    public InputEntry(
            LinkedList<KeyEntry> keyEntries,
            LinkedList<MouseEntry> mouseEntries,
            LinkedList<MouseWheelEntry> mouseWheelEntries,
            LinkedList<MouseEntry> mouseDraggedEntries,
            LinkedList<MouseEntry> mouseMovedEntries,
            LinkedList<MouseMovingEntry> mouseMovingEntries,
            LinkedList<MouseEntry> mouseReleasedQueue
    ) {
        this.keyEntries = keyEntries;
        this.mouseEntries = mouseEntries;
        this.mouseReleasedQueue = mouseReleasedQueue;
        this.mouseWheelEntries = mouseWheelEntries;
        this.mouseDraggedEntries = mouseDraggedEntries;
        this.mouseMovedEntries = mouseMovedEntries;
        this.mouseMovingEntries = mouseMovingEntries;

    }

    /**
     * <p>
     *    A LinkedList of all key entries generated by {@link KeyEvent}.
     * </p>
     *
     * @return Gives all key entries from the keyboard.
     */
    public LinkedList<KeyEntry> getKeyEntries() {
        return this.keyEntries;
    }

    /**
     * <p>
     *    A LinkedList of all key entries generated by {@link MouseAdapter#mousePressed(MouseEvent)}.
     * </p>
     *
     * @return Gives all mouse entries from normal clicks.
     */
    public LinkedList<MouseEntry> getMouseEntries() {
        return this.mouseEntries;
    }

    /**
     * <p>
     *    A LinkedList of all key entries generated by {@link MouseAdapter#mouseReleased(MouseEvent)}.
     * </p>
     *
     * @return Gives all mouse entries from mouse releases.
     */
    public LinkedList<MouseEntry> getMouseReleasedQueue() {
        return this.mouseReleasedQueue;
    }

    /**
     * <p>
     *    A LinkedList of all key entries generated by {@link MouseWheelEvent}.
     * </p>
     *
     * @return Gives all mouse entries from the mouse wheel.
     */
    public LinkedList<MouseWheelEntry> getMouseWheelEntries() {
        return this.mouseWheelEntries;
    }

    /**
     * <p>
     *    A LinkedList of all key entries generated by {@link MouseMotionAdapter#mouseDragged(MouseEvent)}.
     * </p>
     *
     * @return Gives all mouse entries from mouse dragging.
     */
    public LinkedList<MouseEntry> getMouseDraggedEntries() {
        return this.mouseDraggedEntries;
    }

    /**
     * <p>
     *    A LinkedList of all key entries generated by {@link MouseMotionAdapter#mouseMoved(MouseEvent)}.
     * </p>
     *
     * @return Gives all mouse entries from mouse movement.
     */
    public LinkedList<MouseEntry> getMouseMovedEntries() {
        return this.mouseMovedEntries;
    }

    /**
     * <p>
     *    A LinkedList of all key entries generated by {@link de.SweetCode.e.loop.MouseMovingLoop}.
     * </p>
     *
     * @return Gives all mouse entries from mouse movements while they happend.
     */
    public LinkedList<MouseMovingEntry> getMouseMovingEntries() {
        return this.mouseMovingEntries;
    }

    @Override
    public String toString() {
        return ToStringBuilder.create(this)
            .append("keyEntries", this.keyEntries)
            .append("mouseEntries", this.mouseEntries)
            .append("mouseWheelEntries", this.mouseWheelEntries)
            .append("mouseDraggedEntries", this.mouseDraggedEntries)
            .append("mouseMovedEntries", this.mouseMovedEntries)
            .append("mouseMovingEntries", this.mouseMovingEntries)
            .append("mouseReleasedQueue", this.mouseReleasedQueue)
        .build();
    }

}
